# Generated by Django 3.2.25 on 2024-04-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('body_part', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
